// 1. Write a Java program that throws an exception and catch it using a try-catch block.

/* public class Exception_Handling {

    public static void main(String[] args) {
        try {
            int result = divideNumbers(5, 0);
            System.out.println("Result: " + result);
        } catch (ArithmeticException e) {
            // TODO: handle exception
            System.out.println("Error: " + e.getMessage());
        }
    }

    public static int divideNumbers(int divident, int divisor){
        if (divisor==0) {
            throw new ArithmeticException("Division by zero is prohibited");
        }return divident/divisor;
    }
    
}
 */